// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError('Firebase no soportado en Windows');
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGYZFkQ4wlsMrvR9TmpdsX_uYu5Kw2v8A',
    appId: '1:277005442878:web:be2ec6274187a7a732966f',
    messagingSenderId: '277005442878',
    projectId: 'pqxapp',
    authDomain: 'pqxapp.firebaseapp.com',
    storageBucket: 'pqxapp.firebasestorage.app',
    measurementId: 'G-Q9M82V1R6N',
  );



  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL9KI30Cc_aYdFJGXKsDSiRvDOVtFzK0g',
    appId: '1:277005442878:android:e0afabd04c61913432966f',
    messagingSenderId: '277005442878',
    projectId: 'pqxapp',
    storageBucket: 'pqxapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChKDUiZeH3qfzezagHHYVEKvvqBaHl7t8',
    appId: '1:277005442878:ios:d603744d8320b81932966f',
    messagingSenderId: '277005442878',
    projectId: 'pqxapp',
    storageBucket: 'pqxapp.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChKDUiZeH3qfzezagHHYVEKvvqBaHl7t8',
    appId: '1:277005442878:ios:d603744d8320b81932966f',
    messagingSenderId: '277005442878',
    projectId: 'pqxapp',
    storageBucket: 'pqxapp.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGYZFkQ4wlsMrvR9TmpdsX_uYu5Kw2v8A',
    appId: '1:277005442878:web:637f435073379dfa32966f',
    messagingSenderId: '277005442878',
    projectId: 'pqxapp',
    authDomain: 'pqxapp.firebaseapp.com',
    storageBucket: 'pqxapp.firebasestorage.app',
    measurementId: 'G-2BNYSPLJGJ',
  );
}
